### ISSUE TITLE
unnecessary properties in @keyframes

### ISSUE THREAD

**Issue by chuv** [postcss/autoprefixer-core#29]
it's not a critical bug, but without unnecessary properties had better:

Input:
```CSS
@keyframes animation  {
	0% {
		transform: translateY(0); 
	}
	100% {
		transform: translateY(50px);
	}
}
```

Output:
```CSS
@-webkit-keyframes animation {
	0% {
		-webkit-transform: translateY(0);
		transform: translateY(0); /* not need */
	}
	100% {
		-webkit-transform: translateY(50px);
		transform: translateY(50px); /* not need */
	}
}
@keyframes animation {
	0% {
		-webkit-transform: translateY(0); /* not need */
		transform: translateY(0);
	}
	100% {
		-webkit-transform: translateY(50px); /* not need */
		transform: translateY(50px);
	}
}
```
