### ISSUE TITLE
border-image

### ISSUE THREAD

**Issue by CKing** [postcss/autoprefixer-core#47]
According to https://developer.mozilla.org/en-US/docs/Web/CSS/border-image you combine the parameters slice, width and outset with "/"
``` CSS
.box { border-image: url(/images/border.png) 18 / 18px / 5px repeat; }
```

autoprefixer converts this data to
``` CSS
.box { border-image: url(/images/border.png) 0.2px repeat; }
```

This is the result doing the math on these 3 numbers. I don't want to calculate anything, but define width and outset additionally to slice. Right now I am working around this thing by specifying explicitly the width and outset.
