### ISSUE TITLE
values of properties accepting properties should be always output prefixed.

### ISSUE THREAD

**Issue by stratoukos** [postcss/autoprefixer-core#50]
Sorry for the confusing title but here is an example:

```css
div {
    transition-property: filter;
}
```

This will output:

```css
div {
    -webkit-transition-property: -webkit-filter, filter;
            transition-property: filter;
}
```
The result is that browsers that support `transition-property` and `-webkit-filter` will use the second declaration, thus not getting `-webkit-filter`.

The output should probably be:

```css
div {
    -webkit-transition-property: -webkit-filter, filter;
            transition-property: -webkit-filter, filter;
}
```

since there is no guarantee that the same prefix is needed for both sides of the declaration.
