### ISSUE TITLE
Prefix not generated for linear-gradient for Safari 6

### ISSUE THREAD

**Issue by anilnatha** [postcss/autoprefixer-core#52]
I am using the [gulp-autoprefixer](https://github.com/sindresorhus/gulp-autoprefixer) package, which is using autoprefixer-core. I originally reported this [issue](https://github.com/sindresorhus/gulp-autoprefixer/issues/36) to the devs of gulp-autoprefixer, but was told to report it here.

Based on information on [caniuse.com](http://caniuse.com/) for the [linear-gradient](http://caniuse.com/#search=linear-gradient) CSS property, it should be prefixed for Safari 4 through 6.1 (Safari versions 4-5 have partial support for this property).

The following autoprefixer setup:
```javascript
.pipe($.autoprefixer({browsers: ['Explorer > 10','Firefox > 25', 'Safari > 6']}))
```
applied to the following CSS:
```css
.navBar {
	background: linear-gradient(to right, #ba0c2f 0, #410706 100%);
};
```
generates the following CSS, which _should_ include a webkit prefix, but it does not.
```css
.navBar {
  background: linear-gradient(to right, #ba0c2f 0, #410706 100%);
}
```

If I alter the autoprefixer setup to be:
```javascript
.pipe($.autoprefixer({browsers: ['Explorer > 10','Firefox > 25', 'Safari > 5']}))
```
the css appears to be prefixed as it should be:
```css
.navBar {
  background: -webkit-linear-gradient(left, #ba0c2f 0, #410706 100%);
  background: linear-gradient(to right, #ba0c2f 0, #410706 100%);
}
```

Is this a problem with autoprefixer, or is the information about prefixing for Safari 6 for the linear-gradient property inaccurate on caniuse.com?
