### ISSUE TITLE
'transition: filter' does not generate prefixes

### ISSUE THREAD

**Issue by LPGhatguy** [postcss/autoprefixer-core#53]
On the latest npm release of autoprefixer, using `filter` as a `transition` property doesn't seem to be generating a prefixed variant:

Input:
```css
transition: filter 0.3s ease-in-out;
```

Output:
```css
transition: filter 0.3s ease-in-out;
/* prefixed transition variants */
```

Expected Output:
```css
transition: filter 0.3s ease-in-out, -webkit-filter 0.3s ease-in-out, -moz-filter 0.3s ease-in-out;
/* prefixed transition variants */
```

**Comment by ai** [comment]
Autoprefixer already adds `-webkit-filter` to `-webkit-transition` or to just `transition` if there is no `-webkit-transition`.

**Comment by hudochenkov** [comment]
@ai, I have very similar issue.

Config:

```
browsers: ['last 4 versions', '> 1%', 'Android >= 4', 'iOS >= 7']
```

Input:

```css
.wrapper {
    transition: filter .3s;
    filter: blur(10px);
}
```

Output:

```css
.wrapper {
    -webkit-transition: -webkit-filter 0.3s, filter 0.3s;
            transition: filter 0.3s;
    -webkit-filter: blur(10px);
            filter: blur(10px);
}
```

The thing is Chrome 44 supports unprefixed `transition`, but doesn't support unprefixed `filter`. So there is no transition for filter with current output.

![screen shot 2015-07-11 at 23 56 08](https://cloud.githubusercontent.com/assets/654597/8635361/7b379012-2828-11e5-9990-a3db2dea825e.png)

Currently I use this workaround you mentioned in https://github.com/postcss/autoprefixer/issues/299#issuecomment-53595765:

Input:

```css
.wrapper {
    transition: -webkit-filter .3s, filter .3s;
    filter: blur(10px);
}
```

Output:

```css
.wrapper {
    -webkit-transition: -webkit-filter 0.3s, filter 0.3s;
            transition: -webkit-filter 0.3s, filter 0.3s;
    -webkit-filter: blur(10px);
            filter: blur(10px);
}
```
